import Image from 'next/image';
import {assets} from '@/lib/assets';
import NewsCarousel from '@/components/NewsCarousel/NewsCarousel';
import s from './about.module.css';

export const metadata={title:'About Us'};

export default function About(){return <>
  <section className={s.story}>
    <h1>Our Story</h1>
    <div className={s.storyText}><p>Grubox was created to simplify how workplaces access food and snacks. Many offices struggle with limited cafeteria facilities or unreliable food vendors, forcing employees to step out just to grab a quick snack or meal. We saw an opportunity to solve this problem by bringing convenient and reliable food solutions directly into the workplace.</p><p>Our goal was to build a platform that combines technology and food services to make workplace snacking easier, faster, and more accessible. Through smart vending machines, office snack delivery, and micro cafeteria solutions, Grubox helps companies provide employees with fresh snacks and meals without interrupting their workday.</p><p>By integrating cashless payments, smart inventory systems, and automated restocking, Grubox ensures that employees can quickly access food whenever they need it. This approach allows organizations to improve employee convenience while maintaining efficient and hygienic food services within their offices.</p><p>Today, Grubox supports workplaces across Gurgaon and the Delhi NCR region, helping companies create better workplace experiences through modern food solutions.</p><p><b>Grubox is a corporate cafeteria, smart vending and snack delivery platform operated by My Phygital Cafe Private Limited.</b></p></div>
  </section>
  <section className={s.values}><h2>Our Values</h2><p>At Grubox, our mission is to transform the workplace food experience by combining technology, convenience, and quality food services. Our values guide how we serve corporate offices and ensure that every workplace we support receives reliable, hygienic, and efficient food solutions.</p><ul><li>Employee Well-Being First</li><li>Smart Technology Driven Food Access</li><li>Quality, Hygiene, and Food Safety</li><li>Reliable Corporate Service</li><li>Convenience for Modern Workplaces</li><li>Continuous Innovation</li></ul></section>
  <section className={s.vision}><div className={s.visionImage}><Image src={assets.aboutVision} alt="Grubox vision for wellness and sustainability" fill sizes="50vw"/></div><div className={s.visionCopy}><h2>A Vision for Wellness and Sustainability</h2><p>Founded by a team of passionate entrepreneurs, Grubox was built on the vision of creating a wellness-focused, sustainable dining ecosystem for corporate offices. Our founders recognized the need for healthier, more sustainable food options in workplaces and set out to bridge the gap with tech-enabled, eco-friendly solutions.</p><p>From reducing food waste to sourcing responsibly and promoting nutritious meal choices, we are committed to driving a positive impact on workplace well-being while aligning with global sustainability goals.</p></div></section>
  <section className={s.aboutIntro}><div><h2>About Us</h2><h3>From Vending to Smart Corporate Dining</h3><p>At Grubox, we are redefining corporate dining with technology-driven, on-demand cafeteria solutions. What started as a vending service provider has evolved into a comprehensive food tech company, serving businesses of all sizes with fresh, high-quality meals. Our journey began with the simple idea of making workplace snacking more convenient, and today, we power smart cafeterias, bulk meal deliveries, and automated kiosks across corporate offices.</p></div><div className={s.portrait}><Image src={assets.aboutCafe1} alt="Grubox corporate dining" fill sizes="40vw"/></div></section>
  <section className={s.growth}><div className={s.growthRow}><Image src={assets.aboutCafe2} alt="Growing alongside Grubox clients" width={620} height={480}/><article><h3>Growing Alongside Our Clients</h3><p>Our success is built on innovation, partnerships, and customer-first thinking. Over the years, we have scaled alongside our clients, growing from vending machines to full-fledged food service solutions tailored to modern workplaces. With over 80 corporate partnerships, a diversified portfolio of kitchens, kiosks, and vending machines, and a robust tech ecosystem, we ensure a seamless dining experience that boosts employee satisfaction and workplace efficiency.</p></article></div><div className={`${s.growthRow} ${s.reverseRow}`}><article><h3>Tech-Enabled, Seamless Food Solutions</h3><p>Technology is at the heart of Grubox. Our in-house mobile apps, AI-driven ordering systems, and end-to-end ERP solutions allow us to optimize operations, reduce waste, and offer real-time menu customization. With 50,000+ active users and an expanding network of vendors and food partners, we make corporate meals effortless, scalable, and sustainable.</p></article><Image src={assets.aboutCafe3} alt="Grubox technology enabled dining" width={470} height={480}/></div></section>
  <NewsCarousel/>
  <section className={s.commitment}><h3>Our Commitment</h3><p>We are committed to helping organizations create better workplaces by making healthy food, snacks, and beverages easily accessible to employees.</p><p><b>Grubox is a corporate cafeteria, smart vending and snack delivery platform operated by My Phygital Cafe Private Limited.</b></p></section>
  <section className={s.videos}><h2>Videos</h2><div className={s.videoGrid}><iframe src="https://www.youtube.com/embed/8KTIdLTUdDE" title="GruBox How to Use - Desktop Version" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/><iframe src="https://www.youtube.com/embed/Hpi17ywvyDQ" title="Smart Snacking at Work - Grubox Corporate Vending Experience" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div></section>
</>}
