import Image from 'next/image';
import Link from 'next/link';
import {assets} from '@/lib/assets';
import s from './home.module.css';

const reasons=[['Smart Food Technology','Grubox uses smart vending machines and digital systems to make food access quick and seamless in workplaces.'],['Healthy Snack Options','Fresh and nutritious snacks support employee well-being and productivity.'],['Fully Managed Service','From installation to restocking and maintenance, Grubox handles everything for your office.'],['Convenience for Employees','Easy access to snacks saves time and enhances the workplace experience.'],['Flexible Workplace Solutions','Choose smart vending machines, micro cafeterias, or snack delivery services.'],['Reliable Corporate Support','Consistent service and responsive support companies can rely on every day.']];
const clientLogos=['f82157_7b652943d55f4d2a96e680656b693128~mv2.png','496d05_205eb8dc280948ebaecaaad96a6dfee4~mv2.png','f82157_9ccaaa183531407e9c430f9b74593ee0~mv2.jpg','496d05_57659094f9024bb9867bed8a88a085d1~mv2.jpeg','496d05_3864df2324bd47ae98254d10f6711eee~mv2.png','496d05_38f50ac89caa460f89f4479a5537439a~mv2.png','496d05_b8cf4280ee2c406b837c24ba4b939d48~mv2.jpg','496d05_4b30c3dc32f44eeea00fba12328534a6~mv2.jpg','496d05_23c65b1a89bf4672af02265a0d54f08e~mv2.png'].map(id=>`https://static.wixstatic.com/media/${id}/v1/fill/w_106,h_141,q_90,enc_avif,quality_auto/${id}`);
const places=['DLF Cyber Hub','Ambience Mall','Huda City Centre','Sikanderpur','DLF Phase I','DLF Phase II','DLF Phase III','DLF Phase IV','Millennium City','MG Road','U-Block','T-Block','Mayfield Garden','Nathupur','Guru Dronacharya','Gurgaon Sector 17','Gurgaon Sector 18','Gurgaon Sector 24','Gurgaon Sector 26','Gurgaon Sector 27','Gurgaon Sector 44','Gurgaon Sector 45','Gurgaon Sector 48','Gurgaon Sector 50','Gurgaon Sector 52','Gurgaon Sector 53-54','Gurgaon Sector 55-56','Gurgaon Sector 57','Gurgaon Sector 58','Gurgaon Sector 62','Gurgaon Sector 65'];

export default function Home(){return <>
 <section className={s.hero}><Image src={assets.hero} alt="AI-powered Grubox cafeteria" fill priority sizes="100vw"/><div className={s.shade}></div><div className={s.heroText}><h1>AI-Powered Cafeterias<br/>Reimagined</h1><h2>Transforming workplace dining with intelligent solutions.</h2><Link href="/contact-us-vm">Send Enquiry</Link></div></section>
 <section className={s.wellness}><Image src={assets.wellness} alt="Grubox chef preparing healthy meals" width={738} height={604}/><article><h2>Wellness First,<br/>Driving Employee<br/>Engagement</h2><p>At Grubox, we transform office cafeterias into refreshing, energizing spaces where employees can recharge and connect.</p><p>By keeping wellness at the core, we make healthy and fresh food easily accessible while driving up employee engagement and satisfaction.</p></article></section>
 <section className={`${s.feature} ${s.cafe}`}><article><b>Promoting Employee Engagement</b><h2>Enhancing Cafe<br/>Experiences&apos;</h2><i></i><p>Grubox Cafe transforms cafeterias into lively spaces where employees relax, connect, and recharge. Designed for engagement and premium experiences inside corporate environments.</p><Link href="/corporate-cafe">Explore Now</Link></article><Image src={assets.cafe} alt="Grubox managed corporate cafe" width={991} height={906}/></section>
 <section className={`${s.feature} ${s.hospitality}`}><Image src={assets.delivery} alt="Grubox smart hospitality technology" width={862} height={578}/><article><b>Innovative Solutions</b><h2>Smart<br/>Hospitality</h2><i></i><p>Discover a world of nutritious and delicious options at GruBox office deliveries. Our focus is on promoting easy access to healthier eating choices for everyone. From fresh fruits to wholesome snacks, we&apos;ve got you covered. Embrace wellness with every bite and fuel your day with goodness delivered at your office daily.</p><Link href="/grubox-office-deliveries">Explore Now</Link></article></section>
 <section className={`${s.feature} ${s.vending}`}><article><h2>Smart<br/>Vending</h2><p>Discover grubox&apos;s go-to Smart Vending solution for packaged foods. Our innovative machines offer a wide variety of tasty, healthy snacks for those on-the-go With a user-friendly interface, finding and selecting your favorite treats has never been easier. Experience the future of snacking with Grubox!</p><Link href="/vendingmachines">Explore Now</Link></article><Image src={assets.vending} alt="Grubox smart vending machine" width={1118} height={764}/></section>
 <section className={s.why}><h2>Why Grubox</h2><div>{reasons.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><aside className={s.statCards}><article><div><strong>200</strong></div><h3>Clients</h3><p>Trusted by 200+ companies</p><b>→</b></article><article><div><strong>500</strong></div><h3>Vendors</h3><p>Powered by 500+ vendor partners</p><b>→</b></article><article><div><strong>4</strong></div><h3>Million Orders</h3><p>4M+ Orders served</p><b>→</b></article></aside><div className={s.homeGallery}><Image src={assets.cafe} alt="Grubox cafe interior" width={575} height={390}/><Image src={assets.gallery1} alt="Grubox workplace cafe" width={575} height={390}/><Image src={assets.gallery2} alt="Grubox dining service" width={575} height={390}/></div></section>
 <section className={s.testimonials}><p>Customer Reviews &amp; Testimonials</p><h2>Trusted by Leading Workplaces</h2><blockquote>“Grubox vending machines have made snack access extremely<br/>convenient for our employees.”<cite>— Office Admin, Gurgaon</cite></blockquote><div className={s.dots}>● <span>● ● ● ●</span></div><div className={s.logos}>{clientLogos.map((url,index)=><Image key={url} src={url} alt={`Grubox workplace client ${index+1}`} width={133} height={177}/>)}</div>
 <div className={s.blogIntro}><h2>Our Blog</h2><p>Explore blogs on premium offices, employee wellness, sustainability, and healthy office snacking for smarter, healthier workplace dining.</p><div>{[1,2,3].map((n,i)=><Link key={n} href="/blog"><Image src={`/images/blog-card-${n}.avif`} alt="Grubox blog" width={365} height={260}/><b>{['Is a Workplace Food Franchise Better Than a Café Franchise?','Why Office Campuses Are the Future of Food Franchising','Mistakes to Avoid Before Buying a Food Franchise'][i]}</b></Link>)}</div></div></section>
 <section className={s.locations}><div className={s.globe}><Image src="https://static.wixstatic.com/media/11062b_e2b580dab01e420aa08572ba02916d7f~mv2_d_5580_4160_s_4_2.jpg/v1/fill/w_635,h_900,al_c,q_90,enc_avif,quality_auto/globe.jpg" alt="Service locations in Delhi NCR" fill sizes="35vw"/></div><article><h2>Managed Cafeteria Services in Delhi-<br/>NCR</h2><div><section>{places.slice(0,14).map(place=><span key={place}>Managed Cafeteria Services in {place}</span>)}</section><section>{places.slice(14).map(place=><span key={place}>Managed Cafeteria Services in {place}</span>)}</section></div></article></section>
 </>}
