import type {Metadata} from 'next';
import Image from 'next/image';
import s from './vending.module.css';
export const metadata:Metadata={title:'Smart Vending Machines',description:'Customized smart vending solutions by Grubox.'};

const people=[1,2,3,4,5];
const clientFiles=['vending-client-1.jpg','vending-client-2.jpg','vending-client-3.jpg','vending-client-4.png','vending-client-5.png','vending-client-6.jpg','vending-client-7.png','vending-client-8.png','vending-client-9.png'];
const press=[['vending-news-bs.png','Business Standard'],['vending-news-outlook.png','Outlook'],['vending-news-insider.png','Business Insider'],['vending-news-world.png','Businessworld'],['vending-news-entrepreneur.jpg','Entrepreneur India'],['vending-news-yourstory.png','YourStory'],['vending-news-inventiva.png','Inventiva']];

export default function Vending(){return <div className={s.page}>
  <section className={s.hero}><Image src="/images/vending-hero-products.png" alt="Grubox products" fill priority sizes="100vw"/><div className={s.heroCopy}><h1>Grubox Vending Machines</h1><p>Enjoy widest variety of premium quality snacks, drinks and<br/>meals 24X7 at your finger tips!</p><p>Get Grubox for your office space now!</p><a href="/contact-us-vm">Contact Us</a></div><div className={s.wave}/></section>

  <section className={`${s.split} ${s.first}`}><div><h2>Snack Vending Machines by<br/>GruBox – Instant Snacking,<br/>Zero Hassle</h2><p>GruBox snack vending machines provide a seamless, automated snacking experience for corporate offices, co-working spaces, hospitals, and any other high-footfall locations.</p><p>Our vending kiosks offer a curated selection of premium snacks, cashless payments, and AI-powered inventory management for effortless snacking.</p><p>What sets GruBox apart is its healthy food choices, instant refunds, guaranteeing risk-free purchases, and an app-based calorie tracking feature, allowing users to make informed, healthier choices. Upgrade your workplace with GruBox snack vending machines and enjoy smart, contactless snacking with enhanced reliability and transparency.</p></div><Image src="/images/vending-process.png" alt="Grubox vending machine software and happy user" width={1090} height={612}/></section>

  <section className={`${s.split} ${s.reverse}`}><Image src="/images/vending-smart-user.jpeg" alt="Happy user with Grubox vending machine" width={836} height={920}/><div><h2>Smart Vending Machines<br/>by GruBox – AI-Powered<br/>Convenience</h2><p>GruBox smart vending machines redefine automated retail by integrating AI, IoT connectivity, and real-time analytics to create an engaging, frictionless buying experience. Ideal for modern workplaces, tech parks, and corporate hubs.</p><p>Grubox offer touchless transactions, personalized product recommendations, and remote stock monitoring hence <strong>minimising stock outs at your office.</strong></p><p>Our smart vending solutions support multiple cashless payment methods, including UPI, digital wallets, and NFC, making transactions fast and secure.</p><p>Upgrade to GruBox smart vending machines and offer a futuristic, hassle-free retail experience in your space!</p></div></section>

  <section className={`${s.split} ${s.rental}`}><div><h2>Vending Machine Rental<br/>Service by GruBox – No<br/>Hassle, Maximum<br/>Convenience</h2><p>GruBox vending machine rental is the perfect solution for businesses looking to provide smart snacking solution to the employees.</p><p>Whether for corporate offices, co-working spaces, or colleges, our vending kiosks offer a flexible, low-risk way to enhance convenience. With paid subscription services, businesses can enjoy all the benefits of a vending machine without worrying about maintenance, servicing, or stock management—GruBox takes care of everything at your premise.</p><p>Our machines come with customisable product selections, allowing businesses to offer snacks, beverages, or essential items tailored to their audience. Flexible rental plans ensure that companies can choose options that best suit their needs, whether for a short-term event or long-term office use.</p><p>Partner with GruBox for vending machine rental and enjoy a hassle-free, cost-effective way to provide 24/7 access to quality products.</p></div><Image src="/images/vending-rental-user.jpg" alt="Grubox customer using vending machine" width={720} height={652}/></section>

  <section className={s.happiness}><Image className={s.mascot} src="/images/vending-mascot.jpg" alt="Good food is good mood" width={226} height={328}/><h2>Your Box of Happiness Everyday!</h2><div className={s.people}>{people.map(n=><Image key={n} src={`/images/vending-person-${n}.jpg`} alt="Happy Grubox vending customer" width={400} height={800}/>)}</div><div className={s.clientLogos}>{clientFiles.map((file,index)=><Image key={file} src={`/images/${file}`} alt={`Grubox client ${index+1}`} width={180} height={100}/>)}</div></section>

  <section className={s.healthy}><div><h2>Healthy Snacking Made Fun</h2><p>Grubox is fun, everyday! We believe that variety is the key to happier workplaces, which is why Grubox partners with India’s best food brands and handpicks emerging startups that are redefining Indian snacking.</p><p>From healthy twists on traditional favorites to delicious new flavors, our curated cafeteria experiences ensure employees always have something fresh, exciting, and wholesome to look forward to. With a focus on wellness, taste, and quality, Grubox transforms everyday dining into an engaging and sustainable experience.</p><a href="/contact-us-vm">Contact Us</a></div><Image src="/images/vending-healthy.jpg" alt="Healthy snacks at Grubox" width={666} height={666}/></section>

  <section className={s.news}><h2>We are in News</h2><div>{press.map(([file,alt])=><Image key={file} src={`/images/${file}`} alt={alt} width={400} height={150}/>)}</div></section>
</div>}
