import Image from 'next/image';
import PartnerInterestForm from '@/components/PartnerInterestForm/PartnerInterestForm';
import s from './partner.module.css';

export const metadata={title:'Become a Partner'};

const benefits=[
 {title:'Training',image:'/images/partner-training.avif',text:<><p>Empower your franchise journey with Grubox&apos;s comprehensive training program. No more Zomato pressure for your kitchen.</p><p>Our dedicated support team equips you with the expertise to excel in managing a dark store and kitchen services. Through video sessions, on-site training, and ongoing guidance, you&apos;ll master our operations, customer service, business management, inventory management and culinary best practices.</p></>},
 {title:'Marketing',image:'/images/partner-marketing.avif',text:<><p>Boost your business with Grubox&apos;s robust growing platform and marketing support. We have grown 4X in last 3 years and plan to grow to 1000 corporates in next 2 years.</p><p>Our platform crafts tailored content to reach corporate clients, promoting your business through targeted campaigns, sales efforts, social media, and online presence.</p></>},
 {title:'Revenue Potential',image:'/images/partner-revenue.avif',text:<><p>Unlock revenue potential with Grubox cafeteria platform to gain access to lakhs of employees looking for tasty food.</p><p>Our corporate cafeteria management platform caters to the growing demand for convenient, quality food solutions in India&apos;s thriving corporate sector.</p></>}
];
const testimonials=[['“Fresh quick bites have saved me a lot of time. Prices are fit for my daily appetite.”','Sneha, Concentrix'],['"Very convenient to use. Got a prompt response from customer care when i faced an issue."','Sejal, Amex'],['"Very convenient to use. Got a prompt response from customer care when i faced an issue."','Harjeet, Axtria'],['“I love that the menu keeps changing for variety. Choices are healthy and tasty.”','Ritesh,PwC']];

export default function Partner(){return <>
 <section className={s.hero}><div className={s.heroBox}><div className={s.heroCopy}><h1>Become a Grubox Partner -<br/>Start your own food business</h1><h2>Embark on a profitable entrepreneurial journey<br/>with Grubox, India&apos;s leading corporate cafeteria<br/>management platform!</h2><p>Join us as a food franchisee and seize the top franchise opportunity to start your own business in the booming food and beverage industry.</p><p>With Grubox, you&apos;ll leverage our platform in simplifying office snacking, enjoying a proven business model, comprehensive support, and unparalleled customer satisfaction. As one of the best franchisees in India, we offer a lucrative venture for aspiring entrepreneurs.</p><p>Take the first step towards financial independence and become a successful business owner with Grubox.</p></div><Image src="/images/partner-hero.avif" alt="Grubox franchise opportunity" width={626} height={709}/></div></section>
 <section className={s.join}><h2>Join Grubox as a Partner</h2><p className={s.lead}>Grubox Network offers taste, variety and convenience.<br/>With only few simple steps, you can start your food business too!</p><div className={s.cards}>{benefits.map(item=><article key={item.title}><Image src={item.image} alt={`Grubox franchisee ${item.title}`} width={380} height={285}/><div><h3>{item.title}</h3>{item.text}</div></article>)}</div></section>
 <section className={s.clients}><h2>250+ India&apos;s Leading Corporate Clients</h2><div className={s.logoStrip}>{[1,2,3,4,5,6].map(n=><Image key={n} src={`/images/client-${n}.avif`} alt="Grubox corporate client" width={175} height={150}/>)}</div></section>
 <section className={s.technology}><h2>Technology-Driven Success</h2><p>Experience the power of Grubox&apos;s cutting-edge technology, designed to propel your franchise success. Our user-friendly mobile apps enable effortless ordering, while our ERP system streamlines operations, providing real-time insights and efficiency. With Grubox&apos;s technology, you&apos;ll enjoy seamless inventory management, automated reporting, and efficient logistics management, allowing you to focus on growing your business.</p><div className={s.techGallery}><Image src="/images/partner-tech-1.avif" alt="Grubox happy client" width={515} height={290}/><Image src="/images/partner-tech-2.avif" alt="Grubox app use" width={515} height={290}/><Image src="/images/partner-tech-3.avif" alt="Grubox fresh snacks" width={210} height={290}/></div><div className={s.waves}></div></section>
 <section className={s.testimonials}><h2>Our Satisfied Clients :<br/>Testimonials and Success Stories</h2><div className={s.quotes}>{testimonials.map(([quote,name])=><blockquote key={name}><b>”</b><p>{quote}</p><cite>{name}</cite></blockquote>)}</div></section>
 <section className={s.interest}><h2>Share your interest</h2><p>Let us know your email and we will reach out to you!</p><PartnerInterestForm/></section>
 </>}
