import type {Metadata} from 'next';
import s from './terms.module.css';
export const metadata:Metadata={title:'Terms of Service',description:'Rules, policies and guidelines for using GruBox services.'};

export default function Terms(){return <article className={s.terms}>
  <div className={s.inner}>
    <h1>General term of service for the use of the<br/>GruBox platform and GruBox Services</h1>
    <div className={s.lead}>
      <p>Please read the following terms and conditions carefully before registering on, accessing, browsing, downloading or using the GruBox website located at grubox.in, and all associated sites linked to grubox.in, or the GruBox mobile application, or GruBox cloud vending machine and GruBox merchandise fulfilment service or any similar service through GruBox platform (hereinafter collectively, the GruBox run by My Phygital Cafe Pvt. Ltd., office at 8th Floor, Magnum Tower, Sector 58, Gurugram (hereinafter collectively, My Phygital Cafe Pvt. Ltd.(MPC) or GruBox) on any device and/or location before availing any services offered by GruBox on the GruBox Platform which may include services such as closed wallet service, marketplace service or any other service that may be offered by GruBox on the GruBox Platform (hereinafter individually, and collectively, the GruBox Services). For the avoidance of doubt, it is clarified that these terms and conditions shall apply to all GruBox Services, whether offered by My Phygital Cafe Pvt. Ltd. or its affiliates.</p>
      <p>By registering on, accessing, browsing, downloading or using the GruBox for any general purpose or for the specific purpose of availing any GruBox Service, You agree to be bound by the terms and conditions set forth below as well as by the service-specific terms and conditions applicable to each GruBox Service (hereinafter collectively, the T&amp;Cs).</p>
      <p>These T&amp;Cs shall also include any additional or modified terms and conditions in relation to any additional or modified service-specific terms and conditions in relation to any GruBox Service or any future service that may be offered by GruBox on the GruBox Platform. That you hereby grant MPC permission to install, operate, and maintain GruBox (model suitable to serve and sell merchandise) at your premises as per the GruBox requisition form to avail GruBox services. It is understood and agreed that the GruBox installed at your premises is the undisputed property of MPC only.</p>
      <p>The GruBox Services and the GruBox Platform are owned and operated by GruBox. The visual interfaces, graphics, design, compilation, information, computer code (including source code, hardware, firmware and object code), products, software, services, and all other elements of the GruBox Services and the GruBox Platform provided by GruBox (hereafter Materials) are protected by Indian copyright, trade dress, patent, and trademark laws, and all other relevant intellectual property and proprietary rights, and applicable laws. As between you and GruBox, all Materials, trademarks, service marks, and trade names contained on the GruBox Platform are the property of GruBox. The GruBox user registration shall be owned and operated by MPC for use on all Participating Platforms. For the use of GruBox service, the user is required to register. Registration as a user is only allowed if the user meets the eligibility criteria as set out in these T&amp;Cs. Each user can set up only one user account. The user is obliged to provide correct and complete information during the registration and use of the GruBox registration service.</p>
      <p>The login data is intended solely for personal use by the user and therefore always to be kept secret and safe. The user is not entitled to share his login details with third parties to use the GruBox service or to disclose them otherwise. The user is obliged to inform GruBox immediately on becoming aware of and/or suspecting a case of any unauthorized use, disclosure and/or misuse of their access data or of their user account. By completing the mobile number, the user accepts GruBox’s offer, so that in this way this Agreement enters into force.</p>
      <p>You hereby agree that the commercials agreed herein are subject to condition that you will not avail same or similar service for same location from any other vending machine operator. In case of additional requirements, GruBox will remain a preferred service provider. If you still choose any other alternate service provider, GruBox reserves right to revise the commercial terms.</p>
      <p>You hereby agree to provide necessary permissions required to install GruBox at your premises from all the relevant authorities. You will provide the electricity through a dedicated uninterrupted and reliable electricity point with continuous power supply. You will take all care to safeguard the GruBox from theft, vandalism, misuse.</p>
      <p>The clarity, readability, accuracy and promptness of providing the GruBox services, SMS/e-mail alert/push notification relating to the service depend on many factors including the infrastructure and connectivity of the service provider. GruBox will not be responsible for any non-delivery, delayed delivery or distortion of the service in any way whatsoever.</p>
      <p>You hereby agree that GruBox will only be moved or transported or shifted from the installed location by authorised MPC or its channel partners’ personnels only. Any personnels or employees or any person not related to MPC are not allowed to shift or move or transport the GruBox machines without MPC approvals. If GruBox is identified to be shifted or moved or transported from the installation location without prior MPC approval, the company will be liable to penalties as decided solely by MPC.</p>
      <p>You will ensure to cooperate with MPC to remove, withdraw and carry back GruBox at the end of service term expiry and in case either party does not wish to renew further and it terminates by any reason. You hereby agree to arrange necessary documents, approvals and gate pass to outward GruBox from your premises, including permission from SEZ or all relevant authorities, as applicable within 1 month of service term termination.</p>
      <p>In case you sell, transfer or alienate premises of GruBox installation to another party, you will give prior written intimation of at least 30 days to MPC so that negotiations can be made with intending transferee for continuing arrangement. The terms and conditions of this agreement are strictly private and confidential to the parties hereto.</p>
    </div>

    <h2>Damages</h2>
    <p>To the fullest extent permitted by applicable law, in no event shall both party, including its contractors, agents, licensors, partners, suppliers, directors, or employees, or You—be liable to the other for any special, indirect, incidental, consequential, punitive, or exemplary damages. This includes, but is not limited to, loss of profits, business interruption, loss of business opportunities, data loss, or any other pecuniary or non-pecuniary loss, arising out of or in connection with:<br/>(i) this Agreement,</p>
    <p>(ii) the GruBox Services or GruBox Platform, or any referenced site/app/platform/service, or</p><p>(iii) the inability to use or access the GruBox Services or Platform, or</p><p>(iv) any interactions between the both Parties,<br/>even if advised of the possibility of such damages.<br/>Both Parties agree that any liability arising out of or in connection with this Agreement, whether in contract, tort (including negligence), warranty, or otherwise, shall be limited to the total amount paid by You for the use of the GruBox Services or Platform giving rise to the claim, or INR 5,000, whichever is lower.<br/>Both Party shall bear its own liabilities, unless otherwise agreed in writing or mandated by applicable law.</p>
    <p>You acknowledge and agree that GruBox has offered its products and services, set its prices, and entered into this Agreement in reliance upon the warranty disclaimers and the limitations of liability set forth herein, that the warranty disclaimers and the limitations of liability set forth herein reflect a reasonable and fair allocation of risk between You and GruBox, and that the warranty disclaimers and the limitations of liability set forth herein form an essential basis of the bargain between You and GruBox.</p>
    <p>GruBox would not be able to provide the services to You on an economically reasonable basis without these limitations. Applicable law may not completely allow the limitation or exclusion of liability or incidental or consequential damages, so the above limitations or exclusions will apply to You subject to applicable law. In such cases, GruBox’s liability will be limited to the fullest extent permitted by applicable law. This paragraph shall survive the termination of this Agreement.</p>
    <p>GruBox reserves the right to change, modify, add, or remove portions of this Agreement at any time by posting notification on the GruBox Platform or otherwise communicating the notification to You. The changes will become effective, and shall be deemed accepted by You, 24 hours after the initial posting and shall apply immediately on a going-forward basis. If You do not agree with any such change, Your sole and exclusive remedy is to terminate Your use of the GruBox Services/GruBox Platform.</p>
    <p>If any dispute, controversy or claim arises under this Agreement or in relation to any GruBox Service or the GruBox Platform, the parties shall use all reasonable endeavours to resolve such Dispute amicably. If the parties are unable to resolve the Dispute amicably within 30 days, GruBox may elect to resolve it by binding arbitration under the Indian Arbitration &amp; Conciliation Act, 1996. The seat shall be New Delhi and the language English. Any arbitration shall be confidential and each party will bear the expense of its own lawyers and preparation. This paragraph shall survive termination of this Agreement.</p>

    <h2>GruBox Merchandise Service Terms</h2>
    <p>You hereby agree that GruBox are cloud connected machines and delivery are operated on completely automated supply chain model. MPC reserves and, at any point of time, will retain the full control of Merchandise mix, stocking preferences and Merchandise arrangements inside GruBox vending machines and its dark stores. Any suggestions or feedbacks related to Merchandise or its arrangement are subject to commercial viability decided solely by MPC.</p>
    <p>MPC or its channel partner carrying company ID card will visit location periodically for preventive maintenance of GruBox and provide merchandise fulfilment service. MPC and /or its channel partner will regularly service and maintain the GruBoxs and keep them in good working order. The service may be terminated at any time by either party by giving thirty (30) days notice in writing to other party after initial lock in period of 2 months from date of installation of GruBox.</p>
    <h2>Safety Charges and Refund Policy</h2>
    <p>GruBox may charge safety charges as per company policy to its mobile app users. User may have to pay minimal charges on order they place on the mobile app. The safety charges are required to maintain good quality of vending machines and is used towards the welfare of the filling agents. Currently charges are Rs 1 per 3 orders.<br/>To get refunds for orders, initiate the returns process through GruBox or GruBox Consumer App or Customer Care or write to us at care@grubox.in. Refund request is eligible only when the item is not vended successfully. Once refunds are authorised, the following timelines apply:</p>
    <p>PayTM: PayTM Wallet, within 24 hours<br/>Credit/Debit Card: GruBox Wallet refund, within 24 hours<br/>Jio Money: Jio Money, within 24 hours<br/>Bharat QR: Bank Account linked to Bharat QR, 5 Bank working days<br/>GruBox Wallet: Not required, Not required</p>
    <h2>Movement charges</h2><p>GruBox installation, relocation, and removal charges of INR 4000 are mandatory.</p>
    <h2>Invoice Cancelation charges</h2><p>Please be advised that effective immediately, there will be extra charges of INR 500/- for each invoice cancellation. We assure that you receive the monthly invoice in a timely manner at our end. However, we understand that unavoidable circumstances may arise requiring cancellations, but it’s important to note that this incurs additional costs on our end, including administrative expenses, and potential loss of revenue. Your understanding and cooperation in this matter are greatly appreciated.</p>
    <h2>Additional Service Terms</h2><p>You hereby agree to the following additional terms:<br/>GruBox Installation requires the ready setup of the uninterrupted power points for the machine to function.<br/>GruBox machine will enjoy the exclusivity of vending service at the location sites.<br/>Products assortment in the machine will be determined by GruBox platform based on sale and stocks availability. GruBox will start functioning within 72 hours of installation.</p>
    <h2>Unauthorized movement of GruBox is prohibited.</h2><p>GruBox must be installed in a Secure/Guarded location, preferably under camera surveillance. The Client shall bear the duty of care and sole responsibility, to ensure the utmost safeguarding of GruBox against theft, vandalism, misuse, and permanent damage while on the Client’s premises or site.<br/>Invoices will be delivered in digital copy to the Authorized email id, and/or in the preferred delivery mechanism. Any issues should be reported within 3 working days of receiving the invoice.</p><p>All the GruBox service terms are valid till successful removal and end of services of GruBox.<br/>All the dues needs to be cleared for termination of contract.<br/>30 days prior notice is required for termination and removal of GruBox for your premisis.<br/>Full co-operation in smooth removal of the GruBox from the premisis.</p>
    <h2 className={s.caps}>BRANDING AND DATA RIGHTS</h2><p>MPC reserves the rights on branding and data collected on the machine, if any. This will be used for services improvement initiatives and training purposes only.</p>
    <h2 className={s.caps}>PROVISION BY Client</h2><p>The Client shall provide / make necessary provisions for the electricity through a dedicated uninterrupted and reliable electricity point with continuous power supply. The Location must be clean, hygienic, high visibility, properly lit and safe, guarded or under camera surveillance, to ensure smooth usage by the end users.</p>
    <h2 className={s.caps}>OWNERSHIP OF GruBox</h2><p>It is understood and agreed by and between the parties that the GruBox installed on the premises of Client is the undisputed property of MPC only.</p>
    <h2 className={s.caps}>DUTY OF CARE</h2><p>The Client accepts the responsibility along with relevant authorities to safeguard GruBox from theft, vandalism, misuse, permanent damage.</p><p>In the event of disputes with building authorities or any other causes beyond the control of Grubox staff that prevent access to the location or result in the vending machine being unable to generate sales for more than 30 days, the Client shall be liable to pay the Vending Machine Company double the agreed-upon rental fees/ maintenance charges until such time as the vending machine is successfully removed from the location in question.</p><p>In the event of permanent damage to the vending machine or if access to the machine’s location is denied for more than 90 days, the Vending Machine Company reserves the right to charge a recovery amount equivalent to the delivery challan value of the vending machine.</p>
    <h2 className={s.caps}>MAINTENANCE AND SERVICES</h2><p>MPC or its channel Client carrying a company ID card will visit the Location periodically for preventive maintenance of GruBox and fulfillment service. MPC and /or its channel Client shall regularly service and maintain the GruBoxs and keep them in good working order.</p><p>MPC technicians will attend GruBox in case of breakdown and for preventive maintenance. Response time is within 2 working days of reporting an issue.</p>
    <h2 className={s.caps}>DURATION OF SERVICE &amp; TERMINATION OF SERVICE TERMS AND AGREEMENT</h2><p>This agreement and service terms are valid for a term as per requisition form duly filled and signed by client.</p><p>Client shall ensure to cooperate with MPC to uninstall, withdraw and carry back GruBox at the end of agreement expiry and in case either MPC or Client does not wish to renew further and it terminates by any reason. Client agrees to arrange necessary documents, approvals and gate pass to outward GruBox from the Location, including permission from all relevant authorities, as applicable within 1 month of agreement termination.</p><p>In case Client sells, transfers or alienates the Location to another party, Client shall give prior written intimation of at least 30 days to MPC so that negotiations can be made with intending transferee for continuing arrangement.</p>
    <h3>Prohibited Conduct</h3><p>By accessing or using the GruBox Platform or by availing GruBox Services, You agree not to:</p>
    <ul><li>violate the T&amp;Cs;</li><li>impersonate any person or entity, falsely claim or otherwise misrepresent Your affiliation with any person or entity, access the accounts of others without permission, forge another person’s digital signature, or perform any similar fraudulent activity;</li><li>infringe our or any third party’s intellectual property rights, rights of publicity or privacy;</li><li>refuse to cooperate in an investigation or provide confirmation of Your identity or other information;</li><li>remove, circumvent, disable, damage or interfere with security-related features or limitations of the GruBox Platform;</li><li>reverse engineer, decompile, disassemble or attempt to discover source code except where expressly permissible by law;</li><li>use the GruBox Services in a manner that could damage, disable, overburden, or impair it;</li><li>upload or disseminate viruses, adware, spyware, worms, or other malicious code;</li><li>use any robot, spider, automatic device, or manual process to monitor or copy the GruBox Platform without permission;</li><li>interfere with the GruBox Platform or networks connected to it;</li><li>impose an unreasonably or disproportionately large load on GruBox infrastructure;</li><li>provide false, inaccurate or misleading information;</li><li>collect personal or financial information about other users except as expressly provided in the T&amp;Cs;</li><li>use the services in a manner that results in complaints, disputes, chargebacks, fines or other liability;</li><li>take any action that may cause GruBox to lose services, recharge partners, business partners, payment processors or suppliers.</li></ul>
  </div>
</article>}
